# Base config for training poyo_plus

data_root: ./data/processed/
log_dir: ./logs

sequence_length: 1.0  # in seconds
latent_step: 0.125  # in seconds
modality_name: cursor_velocity_2d

epochs: 1000  # if -1, will use steps
steps: -1  # if -1, will use epochs. Epochs take precedence.
eval_epochs: 1

batch_size: 128
eval_batch_size: null  # if null, will use batch_size
num_workers: 4
seed: 42

subtask_weights:
  - 1.0  # RANDOM
  - 0.1  # HOLD
  - 5.0  # REACH
  - 1.0  # RETURN
  - 0.1  # INVALID
  - 0.0  # OUTLIER

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

wandb:
  enable: true
  entity: null
  project: poyo
  run_name: null
  log_model: false

backend_config: gpu_fp32
precision: 32
nodes: 1
gpus: 1

ckpt_path: null  # for resuming training, or loading a model during finetuning

fast_dev_run: false
num_sanity_val_steps: 0