- selection:
    dandiset: "churchland_shenoy"
    sortset: "nitschke_20090812"
  metrics:
    - output_key: CURSORVELOCITY2D
      loss: True
      weight: 1
  exclude_input:
    - UTAH_ARRAY_WAVEFORMS