- selection:
    dandiset: "perich_miller"
  metrics:
    - output_key: CURSORVELOCITY2D
      metric: r2
- selection:
    dandiset: "willett_shenoy"
    output: WRITING_CHARACTER
  metrics:
    - output_key: WRITING_CHARACTER
      metric: accuracy
- selection:
    dandiset: "willett_shenoy"
    output: WRITING_LINE
  metrics:
    - output_key: WRITING_LINE
      metric: accuracy