# Center-out reaching 
- selection:
  - brainset: falcon_m2_2024
    sessions:
      - monkeyn-held_in-calib_20201019_Run1_m2_finger_control
      - monkeyn-held_in-calib_20201019_Run2_m2_finger_control
      - monkeyn-held_in-calib_20201020_Run1_m2_finger_control
      - monkeyn-held_in-calib_20201020_Run2_m2_finger_control
      - monkeyn-held_in-calib_20201027_Run1_m2_finger_control
      - monkeyn-held_in-calib_20201027_Run2_m2_finger_control
      - monkeyn-held_in-calib_20201028_Run1_m2_finger_control
  config:
    multitask_readout:
      - decoder_id: FINGERVELOCITY2D
      # TODO subtasks needed?
        metrics:
          - metric: r2
            task: REACHING
