# Center-out reaching 
- selection:
  - brainset: perich_miller_population_2018
    sessions:
      - t_20130819_center_out_reaching
      # - t_20130821_center_out_reaching
      # - t_20130823_center_out_reaching
      # - t_20130903_center_out_reaching
      # - t_20130905_center_out_reaching
      # - t_20130909_center_out_reaching
  config:
    multitask_readout:
      - decoder_id: CURSORVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 0.1
          REACHING.REACH: 5.0
          REACHING.RETURN: 1.0
          REACHING.INVALID: 0.1
          REACHING.OUTLIER: 0.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.REACH

# # Random target reaching
# - selection:
#   - brainset: perich_miller_population_2018
#     sessions:
#     # - t_20130820_random_target_reaching
#     # - t_20130822_random_target_reaching
#     # - t_20130830_random_target_reaching
#     # - t_20130904_random_target_reaching
#     # - t_20130906_random_target_reaching
#     # - t_20130910_random_target_reaching
#   config:
#     multitask_readout:
#       - decoder_id: CURSORVELOCITY2D
#         subtask_weights:
#           REACHING.RANDOM: 1.0
#           REACHING.HOLD: 0.1
#           REACHING.REACH: 5.0
#           REACHING.RETURN: 1.0
#           REACHING.INVALID: 0.1
#           REACHING.OUTLIER: 0.0
#         metrics:
#           - metric: r2
#             task: REACHING
#             subtask: REACHING.RANDOM
