- selection:
    - dandiset: "mc_maze_small"
  config:
    multitask_readout:
      - decoder_id: ARMVELOCITY2D
        subtask_weights:
          REACHING.RANDOM: 1.0
          REACHING.HOLD: 0.1
          REACHING.REACH: 5.0
          REACHING.RETURN: 1.0
          REACHING.INVALID: 0.1
          REACHING.OUTLIER: 0.0
        metrics:
          - metric: r2
            task: REACHING
            subtask: REACHING.RANDOM
